### ISSUE TITLE
Check whether the RPi OS works on Raspberry Pi 3 Model B+

### ISSUE THREAD

**Issue by s-matyukevich** [s-matyukevich/raspberry-pi-os#1]
I expect everything to work fine, though I don't have this device.

**Comment by lche** [comment]
I accidentally bought a Raspberry Pi 3 Model B+ instead of the 3 Model B. I could give it a try :P

**Comment by s-matyukevich** [comment]
@evopen mentioned that he works with RPi 3 b+ https://github.com/s-matyukevich/raspberry-pi-os/issues/40 I think I can close this issue now.

**Comment by evopen** [comment]
I didn't speak up because I only went through two lessons. I thought that's not gonna be enough. Never mind~

**Comment by sjtugjy** [comment]
I follow the given instructions but fail to see 'hello world' on RPi 3b+. 
:(
Any suggestion?@s-matyukevich

**Comment by zijian-z** [comment]
I meet the same problem on my PI 3b+, @lche Can you run it on your 3b+?

**Comment by lche** [comment]
@zijian-z Sorry, it's been a while since I've touched this. I'll have to confirm later when I have the spare cycles :(

**Comment by sjtugjy** [comment]
Recently, I successfully boot a custom OS on 3b+.

If you want to boot RPi OS on 3b+, maybe you can have a try with adding 'enable_uart=1' in the config.txt.
