### ISSUE TITLE
[Lesson03] qemu Timer question

### ISSUE THREAD

**Issue by avenito** [s-matyukevich/raspberry-pi-os#103]
The timer is not working in qemu.
The code works perfectly on the hardware but on the qemu, after some "debug", I realized that the TIMER_CLO remain zero.

Anyone had this issue?

Thanks

**Comment by s-matyukevich** [comment]
@avargas RPi system time doesn't work on qemu, you should use ARM local timer instead. You can check [this](https://github.com/s-matyukevich/raspberry-pi-os/issues/8#issuecomment-395319084) issue for details.
