### ISSUE TITLE
Confusion in lesson 4

### ISSUE THREAD

**Issue by CkTD** [s-matyukevich/raspberry-pi-os#109]
[Here](https://github.com/s-matyukevich/raspberry-pi-os/blob/master/docs/lesson04/rpi-os.md#memory-allocation) say that [LOW MEMORY](https://github.com/s-matyukevich/raspberry-pi-os/blob/master/src/lesson04/include/mm.h#L13) is 2 MB and [HIGH MEMORY](https://github.com/s-matyukevich/raspberry-pi-os/blob/761eee1cbd709116d0d1235a0085c9c560678391/src/lesson04/include/mm.h#L14) is 1GB - 1MB
> We know the total amount of memory in the system. It is 1 GB - 1 MB (the last megabyte of memory is reserved for device registers) This value is stored in the HIGH_MEMORY constant.

> First 2 MB of memory are reserved for the kernel image and init task stack. This value is stored in LOW_MEMORY constant. All memory allocations start right after this point.

But [here](https://github.com/s-matyukevich/raspberry-pi-os/blob/master/docs/lesson04/rpi-os.md#tracking-system-state-during-a-context-switch), LOW MEMORY is said to be 4 MB.

> The kernel is initialized and kernel_main function is executed. The initial stack is configured to start at LOW_MEMORY, which is 4 MB. 

Is that just a slip of the pen or I get something wrong?

**Comment by s-matyukevich** [comment]
It should be 4 MB. I fixed it https://github.com/s-matyukevich/raspberry-pi-os/commit/87ab517d3f337a0257c7569200dacdd516a6bff0 Thanks for reporting this.
