### ISSUE TITLE
Broken links on caches and multi-core processors in lesson02/linux.md

### ISSUE THREAD

**Issue by reisub0** [s-matyukevich/raspberry-pi-os#110]
Exactly what the title says. Both the links seem to have moved. The caches one has moved to https://developer.arm.com/docs/den0024/latest/caches/cache-maintenance, I think. The multi-processor one, I don't know where it's supposed to point to, so I didn't make a PR.

**Comment by reisub0** [comment]
Line 51.

**Comment by s-matyukevich** [comment]
Hi @reisub0, thanks for reporting this. Links are fixed now https://github.com/s-matyukevich/raspberry-pi-os/commit/db846e617d92e58169b42df2386b7c6c6c9b64d2
