### ISSUE TITLE
getting error while running ./build.sh or ./build.bat docker command not found

### ISSUE THREAD

**Issue by chethanomkar** [s-matyukevich/raspberry-pi-os#114]

**Comment by chethanomkar** [comment]
Hi, actually when i try to run those files i'm getting the error like ./build.sh: line 3: docker: command not found. I earched in the google i couldn't find the solution.

**Comment by s-matyukevich** [comment]
You need to install docker. You can find the link in the [Prerequisites](https://github.com/s-matyukevich/raspberry-pi-os/blob/master/docs/Prerequisites.md)

**Comment by rockytriton** [comment]
you don't need docket to build it, i just ran make

**Comment by s-matyukevich** [comment]
Yes, It will work without docker either if you have aarch64-linux-gnu toolchain installed on your machine.

**Comment by chethanomkar** [comment]
Thank you for all your inputs.
I tried with make, by installing the gcc-aarch64-linux-gnu then the kernel image is generated now.
