### ISSUE TITLE
Raspberry Pi 2?

### ISSUE THREAD

**Issue by RustiRabbit** [s-matyukevich/raspberry-pi-os#117]
Is there anyway that this can work on the Raspberry Pi 2B?
Could I run it on qemu?

**Comment by s-matyukevich** [comment]
@RustiRabbit you can run the OS on qemu, check [this](https://github.com/s-matyukevich/raspberry-pi-os/issues/8) issue for details. You can also check answers to the exercises for some working samples [link](https://github.com/s-matyukevich/raspberry-pi-os/tree/master/exercises/lesson01/4)

You can't run the OS on Raspberry Pi 2

**Comment by RustiRabbit** [comment]
Thanks for letting me know 😊
