### ISSUE TITLE
How to get the value of UARTCLK used by UART

### ISSUE THREAD

**Issue by gcrisis** [s-matyukevich/raspberry-pi-os#120]
In lesson1 exercise 2,I find the way to caculate the baudrate like below,
        BAUDDIV = (FUARTCLK/(16 Baud rate))
but I cannot find the value of FUARTCLK,can anybody help to tell me where can I find the origin about FUARTCLK.
Thank you !

**Comment by s-matyukevich** [comment]
@gcrisis  check this https://github.com/s-matyukevich/raspberry-pi-os/pull/39#issuecomment-398120310

**Comment by gcrisis** [comment]
@s-matyukevich It really helped me a lot. Thank you！
