### ISSUE TITLE
controle ms time with precision  GUI pyqt4 raspberry pi 3

### ISSUE THREAD

**Issue by SERIDJ** [s-matyukevich/raspberry-pi-os#126]
hi someone can help me i need get time with precision ms with python (GUI pyqt4 interface ) in my raspberry PI3
my probleme  i have random error if i test 20ms i have 20ms , 19ms , 15ms, 21ms :((((((
![image](https://user-images.githubusercontent.com/46067255/60032085-27530300-96a6-11e9-8f54-a09b18daf816.png) 

my code test is : 

![image](https://user-images.githubusercontent.com/46067255/60033215-77cb6000-96a8-11e9-878b-dc093cfa6d02.png)

i was tested with thread and i have same error !!!!!!!!
i can use hardware timer with python ????????????????????

**Comment by SERIDJ** [comment]
i someone can help me i need get time with precision ms time with python in my raspberry PI3 i have random error 
![image](https://user-images.githubusercontent.com/46067255/60032085-27530300-96a6-11e9-8f54-a09b18daf816.png)

**Comment by SERIDJ** [comment]
my code test is : 
![image](https://user-images.githubusercontent.com/46067255/60032143-46ea2b80-96a6-11e9-9b87-e4777a250dff.png)

**Comment by s-matyukevich** [comment]
This is not related to Raspberry Pi OS
