### ISSUE TITLE
Translate in Chinese laguage

### ISSUE THREAD

**Issue by gaoljhy** [s-matyukevich/raspberry-pi-os#138]
Hello, I have learned a lot in this Repo.
I want to share it with more Chinese.
Can I translate Chinese for many people?

**Comment by s-matyukevich** [comment]
Hi @gaoljhy. Sure you can. If you want you can make a PR and add the translation to this repo.  If you want to publish it elsewhere it is also fine.

**Comment by gaoljhy** [comment]
Wow ,big thanks 
if i'm done ,i will make a PR right away
