### ISSUE TITLE
Lack of Dutch translations

### ISSUE THREAD

**Issue by mysterybiscuit** [s-matyukevich/raspberry-pi-os#157]
Hey di ho. I would like to create the Dutch translations for this course as I move along it. Would you allow me to do that?

I also do editing for writers, so if you don't mind, I'd like to go through your English and improve it.

**Comment by s-matyukevich** [comment]
Hi @mysterybiscuit , sure this sounds perfect to me!

**Comment by mysterybiscuit** [comment]
Fantabulous. I'll get on it.
