### ISSUE TITLE
IDE Choice? 

### ISSUE THREAD

**Issue by ThexXTURBOXx** [s-matyukevich/raspberry-pi-os#162]
Hello, I would like to start on stuff like this as well, but I don't know which IDE to use.
I used CLion before for my code in C and C++, but afaik, it lacks assembly support.
Which IDE would you recommend? I am using Windows, but have a Ubuntu distribution as VM, which I could use as well, in case Windows isn't the best choice

**Comment by s-matyukevich** [comment]
I am using Vim. VSCode is a good one to.

**Comment by ThexXTURBOXx** [comment]
Ah okay, thank you very much :)
