### ISSUE TITLE
Difference in rpi-os.md -- Should we "Clear FIFO"?

### ISSUE THREAD

**Issue by leoleoasd** [s-matyukevich/raspberry-pi-os#182]
There isn't a "Clear FIFO" line at [here](https://github.com/s-matyukevich/raspberry-pi-os/blame/master/docs/lesson01/rpi-os.md#L295),  but it showed up [here](https://github.com/s-matyukevich/raspberry-pi-os/blame/master/docs/lesson01/rpi-os.md#L370). Which is correct?

Also, I don't know how to make a link with a line number with a markdown file ( which can be done by pressing the line number in other files ), so I'm using the "git blame" to generate a link with a line number.

**Comment by s-matyukevich** [comment]
It is optional, as FIFO is already empty after start, the actual code doesn't use this line https://github.com/s-matyukevich/raspberry-pi-os/blob/master/src/lesson01/src/mini_uart.c#L52

**Comment by leoleoasd** [comment]
So should we remove the "Clear fifo" line cause it is confusing?

**Comment by s-matyukevich** [comment]
Yes, [fixed](https://github.com/s-matyukevich/raspberry-pi-os/commit/8e15715d73cd2dbd247f2fc55f374affd856bd96)
