### ISSUE TITLE
Plan to complete the remaining items

### ISSUE THREAD

**Issue by drymon** [s-matyukevich/raspberry-pi-os#209]
Hi @s-matyukevich I really appreciate what you shared. I wonder if you will spend time to complete the remaining items?

**Comment by s-matyukevich** [comment]
I want to complete the remaining lessons and I even implemented half of the lesson7 functionality, but then I switched to some other personal projects. For now, I am not sure when I'll be able to get back to this one.

**Comment by drymon** [comment]
Understood. Thank you @s-matyukevich !
