### ISSUE TITLE
Linking Documentation Pages

### ISSUE THREAD

**Issue by proph8** [s-matyukevich/raspberry-pi-os#21]
Hey, I'm a newbie in C and OS development. I found this project so interesting and informative to learn C effectively and it's a great way to learn Linux kernel, OS development and Raspberry Pi at the same time! So I'm going to have a few contributions time to time, but I'll be staring from documentation for now.
I wish I'll be able to contribute in code in future soon.

Anyway, as I was reading docs, I made it easier to move through documentation pages for myself by setting "next page" and "previous page" at the end of each doc file to link all pages. readers would continuously have access to next and previous pages easier than before then.

I though this linking feature might be useful enough to make it a pull request, is it?

**Comment by s-matyukevich** [comment]
I like the feature, @proph8 merging this now
