### ISSUE TITLE
The boot problem with Mac and ch340G chip usb2ttl.

### ISSUE THREAD

**Issue by yangyueren** [s-matyukevich/raspberry-pi-os#218]
I have an problem with Mac and ch340G chip usb2ttl. Could someone help me?
When I use `screen /dev/cu.wchusbserial14130 115200` to connect to the original Pi OS, everything goes well. I can login and do everything.
![image](https://user-images.githubusercontent.com/26768698/100963625-b7ff6500-3561-11eb-8a43-5ee27afd7d9f.png)

But after I remove the kernel*.img in the boot and place the kernel8.img, as well as modify the config.txt to 
`kernel_old=1
disable_commandline_tags=1
enable_uart=1`,
I fail to see the hello world.
![image](https://user-images.githubusercontent.com/26768698/100963140-b4b7a980-3560-11eb-8cd7-e80032c6b2ba.png)

![image](https://user-images.githubusercontent.com/26768698/100963219-dd3fa380-3560-11eb-9b8a-12e0bd98c7a6.png)

![image](https://user-images.githubusercontent.com/26768698/100963262-f9434500-3560-11eb-9808-7c89e1f856b1.png)
![image](https://user-images.githubusercontent.com/26768698/100963300-0b24e800-3561-11eb-86ab-7f62b32c313b.png)

_Originally posted by @yangyueren in https://github.com/s-matyukevich/raspberry-pi-os/issues/43#issuecomment-737220879_

**Comment by yangyueren** [comment]
I solved this problem by mofify the config.txt
replace `kernel_old=1`  with `arm_64bit=1`.
this problem is caused by the newer Pi os.

**Comment by yangyueren** [comment]
I solved this problem by modify the config.txt
replace `kernel_old=1`  with `arm_64bit=1`.
this problem is caused by the newer Pi os.

**Comment by rockytriton** [comment]
The new pios also puts you in a different exception level than the older ones, I have some code to revert it to how it was before so you can follow along with the lessons related to exception levels as well:  https://youtu.be/zRhMutscRL0

**Comment by yangyueren** [comment]
> The new pios also puts you in a different exception level than the older ones, I have some code to revert it to how it was before so you can follow along with the lessons related to exception levels as well: https://youtu.be/zRhMutscRL0

Thanks for your quick reply. I will look into it.

**Comment by SunrShine** [comment]
同样的问题，是要在config当中加入arm_64bit=1吗

**Comment by SunrShine** [comment]
![image](https://user-images.githubusercontent.com/48122125/103293578-1f0e1d80-4a2b-11eb-8191-02b76a23d836.png)
when I open the putty and connect the raspberry-pi, there are Garbled codes as the picture shows. 
but if put the **bootcode_delay=5** in to config, using 5 seconds to open the putty and connect the raspberry-pi, it can get the right output.
