### ISSUE TITLE
[Lesson 01] Excerise 3

### ISSUE THREAD

**Issue by szediwy** [s-matyukevich/raspberry-pi-os#222]
Hi there,

I am trying to solve the 3rd exercise for lession 01 on  a Raspberry Pi 4B. So far I could manage 
to adapt all the code for the 4 with the help of the hints in the issues. But I do not manage to 
get all the cores running, just the processor 0.

![image](https://user-images.githubusercontent.com/4198982/104188079-fd446b80-5418-11eb-992c-cb37a248d974.png)

I even built the other user solutions without any success. 

UPDATE: With `uart_2ndstage=1`

![image](https://user-images.githubusercontent.com/4198982/104191463-d50b3b80-541d-11eb-9b99-ab8529a52434.png)

What am I missing? Thanks for you help!

**Comment by szediwy** [comment]
These documents led me to the solution:
[](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/Documentation/arm64/booting.rst?h=v5.3#n255)
[](https://github.com/torvalds/linux/blob/master/arch/arm/boot/dts/bcm2711.dtsi)
[](https://github.com/raspberrypi/tools/blob/master/armstubs/armstub8.S)

**Comment by szediwy** [comment]
Found a solution.

**Comment by hwangs12** [comment]
Hi @szediwy, how did it occur to you that this could be a solution? 

<img width="149" height="183" alt="Image" src="https://github.com/user-attachments/assets/89baf02e-a00e-46c7-8c7e-4cf92fbcb380" />

I don't mean it sarcastically but out of respect. Can you kind of explain how you come to this solution, a little more than reading documentation you provided? 

First you save program counter of *master* into x0 then you store that into memory address saved in x1 but we later just overwrite x1 with new data to sp. 

Can this \#0xx be any value? I am just mesmerized of the fact that the things we could do with ARM assembly and not understanding it will never get me to a solution by myself, which is pretty sad.
