### ISSUE TITLE
Raspberry Pi Zero support

### ISSUE THREAD

**Issue by nemo8** [s-matyukevich/raspberry-pi-os#24]
Hi,

Is it possible to work with your OS under Raspberry Pi Zero?

Thanks,
Vasyl

**Comment by s-matyukevich** [comment]
@nemo8  you need  64 bit processor to run RPi OS, so unfortunately not.

**Comment by s-matyukevich** [comment]
@nemo8 I'm closing this now, feel free to reopen if you have additional questions.
