### ISSUE TITLE
Typo on: 1.4: Linux startup sequence

### ISSUE THREAD

**Issue by Sustrak** [s-matyukevich/raspberry-pi-os#25]
In the section Device Tree in the seventh paragraph:

> A device tree definition consists of the blocks nested one in another. At the top level we usually can find such blocks as cpus or memory The meaning of those blocks should be quite self-explanatory. Another interesting top-level element that we can find in the bcm283x.dtsi is **sos** that means System on a chip It tells us that all peripheral devices are directly mapped to some memory area via memory mapped registers. soc element serves as a parent element for all peripheral devices. One of its children is gpio element. This element defines reg = <0x7e200000 0xb4> property that tells us that GPIO memory mapped registers are located in the [0x7e200000 : 0x7e2000b4] region. One of the childern of gpio element has the following definition

**sos** should be **SoC** as Wikipedia points out:

> A system on a chip or system on chip (SoC or SOC)

**Comment by s-matyukevich** [comment]
Thanks @Sustrak , merged
