### ISSUE TITLE
Bug in function free_page

### ISSUE THREAD

**Issue by lizhuohua** [s-matyukevich/raspberry-pi-os#32]
The current version is:
```
void free_page(unsigned long p){
	mem_map[p / PAGE_SIZE] = 0;
}
```
I guess you forgot to subtract LOW_MEMORY here. It should be:
```
void free_page(unsigned long p){
	mem_map[(p - LOW_MEMORY) / PAGE_SIZE] = 0;
}
```

**Comment by s-matyukevich** [comment]
Fixed [here](https://github.com/s-matyukevich/raspberry-pi-os/commit/b55f5fb4a478350dfaf96154d023dbccb7443333) Closing this now.
