### ISSUE TITLE
Revised BCM2837(5)-ARM-Peripherals

### ISSUE THREAD

**Issue by evopen** [s-matyukevich/raspberry-pi-os#38]
There is a homemade revised version of BCM2837 peripherals. If you don't want to check errata page all the time.

[Here is the original post](https://github.com/raspberrypi/documentation/issues/325#issuecomment-379651504)
[And the download link](https://github.com/raspberrypi/documentation/files/1888662/BCM2837-ARM-Peripherals.-.Revised.-.V2-1.pdf)

btw, I don't know why the download link is linked to rpi official repo.

**Comment by s-matyukevich** [comment]
Perfect! I will add this libk to the lesson 1.

**Comment by s-matyukevich** [comment]
Done https://github.com/s-matyukevich/raspberry-pi-os/commit/b3d3cedfc21c2ac06da9fe085c97c2f283cddb08
