### ISSUE TITLE
Kernel code reading environment

### ISSUE THREAD

**Issue by evopen** [s-matyukevich/raspberry-pi-os#58]
Hey I'm wondering is there any recommendations for reading (editing) kernel source code. 

I know this is a personal preference thing. But I still would like to get some opinions. 

I have been using emacs for the last two years in terminal. C/S mode is making it super fast which is better than vim.  Clion is amazing but sadly it doesn't support Makefile. 

I know a Android kernel developer. His kernel is good(at least I think so) and he's productive(based on commit history). And he told me that he uses vscode. 
Hum... I don't know... vscode doesn't even have built-in asm highlighting. 

I switched to vim from spacemacs a month ago. But frankly they are the same in general that they rely on gtags and cscope. And I feel lag reading and jumping around function calls.

What about QT Creator? I haven't tried it.

**Comment by s-matyukevich** [comment]
I use vim + cscope + some plugins like NerdTree, thought I'am not quite happy with the cscope experience when searching for symbol usage, symbol definition, etc. A lot of times I have to rely on grep and  complicated regexp expressions. It would be nice if somebody can share a better way of working with kernel source.
