### ISSUE TITLE
[Lesson06] LSR instruction

### ISSUE THREAD

**Issue by xharrym** [s-matyukevich/raspberry-pi-os#67]
There is a mistake in the explanation of this snippet of code for the macro `create_table_entry`:
```
   lsr    \tmp1, \virt, #\shift
    and    \tmp1, \tmp1, #PTRS_PER_TABLE - 1            // table index
```

The instruction `LSR` stands for logical shift *right*, not left as it  is explained in the text? http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.dui0497a/BABJCCDH.html

**Comment by s-matyukevich** [comment]
Fixed https://github.com/s-matyukevich/raspberry-pi-os/commit/40df8c36fa3be3f4c13b1733ebd78ea475509195 
Thanks @xharrym
