### ISSUE TITLE
I got a problem about using docker to build

### ISSUE THREAD

**Issue by LBBym** [s-matyukevich/raspberry-pi-os#78]
Hello!
I‘m using dockertools in Winsows10 . 
the command in my build.bat is
`docker run --rm -v %cd%:/app -w /app smatyukevich/raspberry-pi-os-builder make %1`
I think it's just the same as the command in the repo. But everytime I try to run `./build.bat` in powershell, it would say `docker: Error response from daemon: invalid mode: /app.
See 'docker run --help'.` I've already search in the internet and still can't work it out. 
Could anybody help me out? 
Thanks a lot!

**Comment by s-matyukevich** [comment]
@LBBym I think that %cd% works only in Windows Command Line (cmd), but not in PowerShell. Can you try replacing it with `$(pwd)`?  You can also try to run `build.bat` from cmd. Check [this](https://stackoverflow.com/questions/41485217/mount-current-directory-as-volume-in-docker-on-windows-10) question for reference.

**Comment by LBBym** [comment]
Thanks a lot !
I've fixed it
