### ISSUE TITLE
[Feature Request] Create a git pages site

### ISSUE THREAD

**Issue by mkarpoff** [s-matyukevich/raspberry-pi-os#85]
This is a feature request/suggestion. 
The layout for this git repo is in prime shape to be setup as a git pages website. This would make viewing the lessons easier as the text would fill the screen.

**Comment by s-matyukevich** [comment]
That's a good idea. I published the project here: https://s-matyukevich.github.io/raspberry-pi-os/

**Comment by mkarpoff** [comment]
Absolutely gorgeous. I'll close this.
