### ISSUE TITLE
Data abort in show_invalid_entry_message

### ISSUE THREAD

**Issue by bl4ckout31** [s-matyukevich/raspberry-pi-os#86]
The entry_error_messages array is missing the messages for error 15 and 16 (SYNC_ERROR and SYSCALL_ERROR respectively) which causes a `data abort` when trying to access them in the `show_invalid_entry_message` function.

To reproduce: 
- Use code from lesson05
- Comment out line 162 in `entry.S`

**Comment by s-matyukevich** [comment]
Thanks! Closing this now.
