### ISSUE TITLE
Lesson 1.1 explains the wrong ARM instruction lrd vs. adr

### ISSUE THREAD

**Issue by andrewstockwell** [s-matyukevich/raspberry-pi-os#9]
Under the **Booting the Kernel** header, the ARM instruction `lrd` is explained when the `adr` instruction is used instead. This one was confusing for me as someone familiar with asm but not with ARM.

[adr (PC-relative)](http://www.keil.com/support/man/docs/armasm/armasm_dom1361358903373.htm) seems to be the correct instruction.

It might be nice to link every instruction to the proper URL as well. I'm happy to fork this and fix it!

**Comment by s-matyukevich** [comment]
Thanks for the PR @andrewstockwell it is merged now, closing this issue.
