### ISSUE TITLE
Adapt design into RTOS?

### ISSUE THREAD

**Issue by JohnPeng47** [s-matyukevich/raspberry-pi-os#91]
I've recently took a course about Real Time Operating Systems, and was wondering, how difficult would it be to adapt the current OS design into a bare-bones RTOS?

**Comment by s-matyukevich** [comment]
@JohnPeng47 I am not very familiar with RTOS design, but as far as I understand an RTOS should have more advanced scheduling algorithms and provide some guarantees about how fast a process should be waked in case some signal arrives Currently the RPi OS don't support signals and waitlists (it should be implemented in the lesson 7) Only after this functionality is ready we can discuss how to adopt the RPi OS to be an RTOS.
