### ISSUE TITLE
get more cheaper and better respberry pi 

### ISSUE THREAD

**Issue by x-lugoo** [s-matyukevich/raspberry-pi-os#98]
https://www.amazon.com/gp/product/B07BFH96M3/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=B07BFH96M3&linkCode=as2&tag=a294p4x9ewv02-20&linkId=294b1e6b1bb324290f0586f3653f0e04

**Comment by s-matyukevich** [comment]
What is the difference from the one mentioned in the Prerequisites? Anyway, I would rather prefer to use a link to the official RPi website.

**Comment by x-lugoo** [comment]
Yes ,you are right
