### ISSUE TITLE
Why are we compiling assembly files using GCC instead of GAS?

### ISSUE THREAD

**Issue by dublevsky** [s-matyukevich/raspberry-pi-os#99]
Hi, wanted to know what's the reason in compiling .S files using GCC rather than GAS. Is it because of "-MMD" flag?

P. S. I think there should be some kind of IRC or Discord channel to ask these kinds of questions instead of polluting the "Issues".

**Comment by s-matyukevich** [comment]
We need GCC because we want to reuse in the assembler code some macros defined in the header files. Otherwise, we will have to duplicate a lot of constants and define them separately for C and assembler code.

**Comment by s-matyukevich** [comment]
@dublevsky I think I'll create a slack channel to simplify the communication.

**Comment by s-matyukevich** [comment]
I've added a link to the slack channel in the readme. Closing this issue now.
